import type { Metadata } from "next";
import "@/styles/globals.css";
import { poppins } from "@/fonts";
import { AppThemeProvider } from "@/provider/app-theme-provider";
import { Layout } from "@/shared/components/root-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AppThemeProvider>
          <Layout>{children}</Layout>
        </AppThemeProvider>
      </body>
    </html>
  );
}
